export let CustomerOrder=[
    {
        
          tableNo: 25,
          customer: "Dhiraj Temkar",
          dishSelected: [
            {
              id: 2,
              name: "Mutton Biryani",
              count: 2,
              total: 80,
              isCustomized: true,
              customOptions: {
                size: "ExtraLarge",
                select: ["cheeseBurst", "Spicy", "Jyada Lao"],
              },
              rating: 4,
              price: 40,
              checkHai: true,
            },
            {
              id: 1,
              name: "McAloBurger",
              count: 3,
              total: 60,
              isCustomized: false,
              customOptions: {},
              rating: 3,
              price: 20,
              checkHai: true,
            },
            {
              id: 5,
              name: "Mutton Biryani",
              count: 2,
              total: 80,
              isCustomized: true,
              customOptions: {
                size: "ExtraLarge",
                select: ["cheeseBurst", "Spicy", "Jyada Lao"],
              },
              rating: 4,
              price: 40,
              checkHai: true,
            },
            {
              id: 3,
              name: "Limbu Sharbat",
              count: 2,
              total: 20,
              isCustomized: true,
              customOptions: {
                size: "Medium",
                select: ["ExtraCold", "straw dena"],
              },
              rating: 5,
              price: 10,
              checkHai: true,
            },
          ],
          id: '0',
          total: 210,
          code: "#213074",
          date: "09-08-2020",
          hotelName: "Brinda's Cafe",
          // time: comp.time,
          // image: comp.hotelImage,
          locality: "Santacruz East, Mumbai",
          Status: "New",
          orderBuild: true, // update if order cancle
          orderState: "prep",
    },
    {
        
        tableNo: 25,
        customer: "Dhiraj Temkar",
        dishSelected: [
          {
            id: 2,
            name: "Mutton Biryani",
            count: 2,
            total: 80,
            isCustomized: true,
            customOptions: {
              size: "ExtraLarge",
              select: ["cheeseBurst", "Spicy", "Jyada Lao"],
            },
            rating: 4,
            price: 40,
            checkHai: true,
          },
          {
            id: 1,
            name: "McAloBurger",
            count: 3,
            total: 60,
            isCustomized: false,
            customOptions: {},
            rating: 3,
            price: 20,
            checkHai: true,
          },
          {
            id: 5,
            name: "Mutton Biryani",
            count: 2,
            total: 80,
            isCustomized: true,
            customOptions: {
              size: "ExtraLarge",
              select: ["cheeseBurst", "Spicy", "Jyada Lao"],
            },
            rating: 4,
            price: 40,
            checkHai: true,
          },
          {
            id: 3,
            name: "Limbu Sharbat",
            count: 2,
            total: 20,
            isCustomized: true,
            customOptions: {
              size: "Medium",
              select: ["ExtraCold", "straw dena"],
            },
            rating: 5,
            price: 10,
            checkHai: true,
          },
        ],
        id: '1',
        total: 210,
        code: "#213074",
        date: "09-08-2020",
        hotelName: "Brinda's Cafe",
        // time: comp.time,
        // image: comp.hotelImage,
        locality: "Santacruz East, Mumbai",
        Status: "New",
        orderBuild: true, // update if order cancle
        orderState: "Generate",
  },
  {
        
    tableNo: 25,
    customer: "Dhiraj Temkar",
    dishSelected: [
      {
        id: 2,
        name: "Mutton Biryani",
        count: 2,
        total: 80,
        isCustomized: true,
        customOptions: {
          size: "ExtraLarge",
          select: ["cheeseBurst", "Spicy", "Jyada Lao"],
        },
        rating: 4,
        price: 40,
        checkHai: true,
      },
      {
        id: 1,
        name: "McAloBurger",
        count: 3,
        total: 60,
        isCustomized: false,
        customOptions: {},
        rating: 3,
        price: 20,
        checkHai: true,
      },
      {
        id: 5,
        name: "Mutton Biryani",
        count: 2,
        total: 80,
        isCustomized: true,
        customOptions: {
          size: "ExtraLarge",
          select: ["cheeseBurst", "Spicy", "Jyada Lao"],
        },
        rating: 4,
        price: 40,
        checkHai: true,
      },
      {
        id: 3,
        name: "Limbu Sharbat",
        count: 2,
        total: 20,
        isCustomized: true,
        customOptions: {
          size: "Medium",
          select: ["ExtraCold", "straw dena"],
        },
        rating: 5,
        price: 10,
        checkHai: true,
      },
    ],
    id: '2',
    total: 210,
    code: "#213074",
    date: "09-08-2020",
    hotelName: "Brinda's Cafe",
    // time: comp.time,
    // image: comp.hotelImage,
    locality: "Santacruz East, Mumbai",
    Status: "New",
    orderBuild: true, // update if order cancle
    orderState: "prep",
},
{
        
    tableNo: 25,
    customer: "Dhiraj Temkar",
    dishSelected: [
      {
        id: 2,
        name: "Mutton Biryani",
        count: 2,
        total: 80,
        isCustomized: true,
        customOptions: {
          size: "ExtraLarge",
          select: ["cheeseBurst", "Spicy", "Jyada Lao"],
        },
        rating: 4,
        price: 40,
        checkHai: true,
      },
      {
        id: 1,
        name: "McAloBurger",
        count: 3,
        total: 60,
        isCustomized: false,
        customOptions: {},
        rating: 3,
        price: 20,
        checkHai: true,
      },
      {
        id: 5,
        name: "Mutton Biryani",
        count: 2,
        total: 80,
        isCustomized: true,
        customOptions: {
          size: "ExtraLarge",
          select: ["cheeseBurst", "Spicy", "Jyada Lao"],
        },
        rating: 4,
        price: 40,
        checkHai: true,
      },
      {
        id: 3,
        name: "Limbu Sharbat",
        count: 2,
        total: 20,
        isCustomized: true,
        customOptions: {
          size: "Medium",
          select: ["ExtraCold", "straw dena"],
        },
        rating: 5,
        price: 10,
        checkHai: true,
      },
    ],
    id: '3',
    total: 210,
    code: "#213074",
    date: "09-08-2020",
    hotelName: "Brinda's Cafe",
    // time: comp.time,
    // image: comp.hotelImage,
    locality: "Santacruz East, Mumbai",
    Status: "New",
    orderBuild: true, // update if order cancle
    orderState: "new",
},
{
        
    tableNo: 25,
    customer: "Dhiraj Temkar",
    dishSelected: [
      {
        id: 2,
        name: "Mutton Biryani",
        count: 2,
        total: 80,
        isCustomized: true,
        customOptions: {
          size: "ExtraLarge",
          select: ["cheeseBurst", "Spicy", "Jyada Lao"],
        },
        rating: 4,
        price: 40,
        checkHai: true,
      },
      {
        id: 1,
        name: "McAloBurger",
        count: 3,
        total: 60,
        isCustomized: false,
        customOptions: {},
        rating: 3,
        price: 20,
        checkHai: true,
      },
      {
        id: 5,
        name: "Mutton Biryani",
        count: 2,
        total: 80,
        isCustomized: true,
        customOptions: {
          size: "ExtraLarge",
          select: ["cheeseBurst", "Spicy", "Jyada Lao"],
        },
        rating: 4,
        price: 40,
        checkHai: true,
      },
      {
        id: 3,
        name: "Limbu Sharbat",
        count: 2,
        total: 20,
        isCustomized: true,
        customOptions: {
          size: "Medium",
          select: ["ExtraCold", "straw dena"],
        },
        rating: 5,
        price: 10,
        checkHai: true,
      },
    ],
    id: '4',
    total: 210,
    code: "#213074",
    date: "09-08-2020",
    hotelName: "Brinda's Cafe",
    // time: comp.time,
    // image: comp.hotelImage,
    locality: "Santacruz East, Mumbai",
    Status: "New",
    orderBuild: true, // update if order cancle
    orderState: "ready",
},
{
        
  tableNo: 25,
  customer: "Dhiraj Temkar",
  dishSelected: [
    {
      id: 2,
      name: "Mutton Biryani",
      count: 2,
      total: 80,
      isCustomized: true,
      customOptions: {
        size: "ExtraLarge",
        select: ["cheeseBurst", "Spicy", "Jyada Lao"],
      },
      rating: 4,
      price: 40,
      checkHai: true,
    },
    {
      id: 1,
      name: "McAloBurger",
      count: 3,
      total: 60,
      isCustomized: false,
      customOptions: {},
      rating: 3,
      price: 20,
      checkHai: true,
    },
    {
      id: 5,
      name: "Mutton Biryani",
      count: 2,
      total: 80,
      isCustomized: true,
      customOptions: {
        size: "ExtraLarge",
        select: ["cheeseBurst", "Spicy", "Jyada Lao"],
      },
      rating: 4,
      price: 40,
      checkHai: true,
    },
    {
      id: 3,
      name: "Limbu Sharbat",
      count: 2,
      total: 20,
      isCustomized: true,
      customOptions: {
        size: "Medium",
        select: ["ExtraCold", "straw dena"],
      },
      rating: 5,
      price: 10,
      checkHai: true,
    },
  ],
  id: '5',
  total: 210,
  code: "#213074",
  date: "09-08-2020",
  hotelName: "Brinda's Cafe",
  // time: comp.time,
  // image: comp.hotelImage,
  locality: "Santacruz East, Mumbai",
  Status: "New",
  orderBuild: true, // update if order cancle
  orderState: "ready",
},
{
        
  tableNo: 25,
  customer: "Dhiraj Temkar",
  dishSelected: [
    {
      id: 2,
      name: "Mutton Biryani",
      count: 2,
      total: 80,
      isCustomized: true,
      customOptions: {
        size: "ExtraLarge",
        select: ["cheeseBurst", "Spicy", "Jyada Lao"],
      },
      rating: 4,
      price: 40,
      checkHai: true,
    },
    {
      id: 1,
      name: "McAloBurger",
      count: 3,
      total: 60,
      isCustomized: false,
      customOptions: {},
      rating: 3,
      price: 20,
      checkHai: true,
    },
    {
      id: 5,
      name: "Mutton Biryani",
      count: 2,
      total: 80,
      isCustomized: true,
      customOptions: {
        size: "ExtraLarge",
        select: ["cheeseBurst", "Spicy", "Jyada Lao"],
      },
      rating: 4,
      price: 40,
      checkHai: true,
    },
    {
      id: 3,
      name: "Limbu Sharbat",
      count: 2,
      total: 20,
      isCustomized: true,
      customOptions: {
        size: "Medium",
        select: ["ExtraCold", "straw dena"],
      },
      rating: 5,
      price: 10,
      checkHai: true,
    },
  ],
  id: '6',
  total: 210,
  code: "#213074",
  date: "09-08-2020",
  hotelName: "Brinda's Cafe",
  // time: comp.time,
  // image: comp.hotelImage,
  locality: "Santacruz East, Mumbai",
  Status: "New",
  orderBuild: true, // update if order cancle
  orderState: "Generate",
},
{
        
  tableNo: 25,
  customer: "Dhiraj Temkar",
  dishSelected: [
    {
      id: 2,
      name: "Mutton Biryani",
      count: 2,
      total: 80,
      isCustomized: true,
      customOptions: {
        size: "ExtraLarge",
        select: ["cheeseBurst", "Spicy", "Jyada Lao"],
      },
      rating: 4,
      price: 40,
      checkHai: true,
    },
    {
      id: 1,
      name: "McAloBurger",
      count: 3,
      total: 60,
      isCustomized: false,
      customOptions: {},
      rating: 3,
      price: 20,
      checkHai: true,
    },
    {
      id: 5,
      name: "Mutton Biryani",
      count: 2,
      total: 80,
      isCustomized: true,
      customOptions: {
        size: "ExtraLarge",
        select: ["cheeseBurst", "Spicy", "Jyada Lao"],
      },
      rating: 4,
      price: 40,
      checkHai: true,
    },
    {
      id: 3,
      name: "Limbu Sharbat",
      count: 2,
      total: 20,
      isCustomized: true,
      customOptions: {
        size: "Medium",
        select: ["ExtraCold", "straw dena"],
      },
      rating: 5,
      price: 10,
      checkHai: true,
    },
  ],
  id: '7',
  total: 210,
  code: "#213074",
  date: "09-08-2020",
  hotelName: "Brinda's Cafe",
  // time: comp.time,
  // image: comp.hotelImage,
  locality: "Santacruz East, Mumbai",
  Status: "New",
  orderBuild: true, // update if order cancle
  orderState: "new",
},
]